"""MediProof contracts — the single source of truth (see CLAUDE.md).

Import types from this package, e.g. `from schemas import ClaimFile, DocType`.
"""

from schemas.claim import (
    ClaimFile,
    ClaimStatus,
    CompletenessReport,
    Correction,
    DocumentRecord,
    PageInfo,
)
from schemas.common import (
    AMBER_THRESHOLD,
    GREEN_THRESHOLD,
    BBox,
    ConfidenceBand,
    DocType,
    Evidence,
    ExtractedField,
    FieldSource,
    Gender,
    Money,
    Severity,
    band_for,
)
from schemas.documents import (
    ExtractedDischargeSummary,
    ExtractedDocument,
    ExtractedHospitalBill,
    ExtractedLabReport,
    ExtractedPharmacyBill,
    ExtractedPrescription,
)
from schemas.findings import Finding, FindingType
from schemas.ground_truth import (
    FAULT_TO_FINDING,
    BillCategory,
    BillLineItem,
    ClaimGroundTruth,
    DischargeSummaryGT,
    DocumentGT,
    FaultLabel,
    FaultType,
    HospitalBillGT,
    HospitalInfo,
    LabReportGT,
    Medication,
    PatientInfo,
    PharmacyBillGT,
    PharmacyLineItem,
    PrescriptionGT,
)

__all__ = [
    "AMBER_THRESHOLD",
    "GREEN_THRESHOLD",
    "BBox",
    "BillCategory",
    "BillLineItem",
    "ClaimFile",
    "ClaimGroundTruth",
    "ClaimStatus",
    "CompletenessReport",
    "ConfidenceBand",
    "Correction",
    "DischargeSummaryGT",
    "DocType",
    "DocumentGT",
    "DocumentRecord",
    "Evidence",
    "ExtractedDischargeSummary",
    "ExtractedDocument",
    "ExtractedField",
    "ExtractedHospitalBill",
    "ExtractedLabReport",
    "ExtractedPharmacyBill",
    "ExtractedPrescription",
    "FAULT_TO_FINDING",
    "FaultLabel",
    "FaultType",
    "FieldSource",
    "Finding",
    "FindingType",
    "Gender",
    "HospitalBillGT",
    "HospitalInfo",
    "LabReportGT",
    "Medication",
    "Money",
    "PageInfo",
    "PatientInfo",
    "PharmacyBillGT",
    "PharmacyLineItem",
    "PrescriptionGT",
    "Severity",
    "band_for",
]
